name: Packaging
on: pull_request

jobs:
  release-tarball:
    runs-on: ubuntu-latest
    name: Build release tarball
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Set up Node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: 15
      - name: Set up php$
        uses: shivammathur/setup-php@a870b0a9be03fabbba4c6dbf1af1260c0e4d4893
        with:
          php-version: 8.0
          tools: composer
          extensions: ctype,curl,dom,gd,iconv,intl,json,mbstring,openssl,posix,sqlite,xml,zip,gmp
          coverage: none
      - name: Install Krankerl
        run: |
          wget https://github.com/ChristophWurst/krankerl/releases/download/v0.14.0/krankerl_0.14.0_amd64.deb
          sudo dpkg -i krankerl_0.14.0_amd64.deb
      - name: Package app
        run: krankerl package
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          path: build/artifacts/calendar.tar.gz
          if-no-files-found: error
